name: 'update moment'
description: '拉取issues生成moment markdown文件'
inputs:
  token:
    description: 'github token'
    default: ${{ github.token }}
  momentLabels:
    description: 'issue labels'
    default: 'moment'
  momentPath:
    description: 'moment markdown file path'
    default: 'source/moment/index.md'
  postsLabels:
    description: 'posts labels'
    default: 'moment'
  postsPath:
    description: 'posts markdown directory path'
    default: 'source/_posts'
outputs:
  content:
    description: 'issue moment content'

runs:
  using: 'node16'
  main: 'dist/index.js'