name: build site

on:
  push:
    branches: [master]
  workflow_dispatch:
  issues:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: install dependencies
        run: npm install

      - name: fetch issue data
        run: |
          export GITHUB_TOKEN=$GITHUB_TOKEN
          npm run fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add source/moment/
          git add source/_posts/
          if ! git diff --quiet HEAD; then
            git commit -m "update moment and posts close #${{ github.event.issue.number }}"
            git push
          fi

      - name: build site
        run: npm run build
    
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: qwertyyb@foxmail.com
          build_dir: public
          branch: gh-pages
          jekyll: no
          commit_message: "update site"
        
      - name: upload pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: public
