name: build site

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm install
      
      - name: build site
        run: npm run build
        
      - name: upload pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: public
    
      - name: update site
        run: |
          git config user.email "qwertyyb@foxmail.com"
          git config user.name "qwertyyb"
          npm run deploy
