name: build site

on:
  push:
    branch: [master]


jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      - name: install theme
        run: npm run theme:install
      
      - name: build site
        run: npm run build
        
      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
    
      - name: update site
        uses: actions/deploy-pages@v1
