name: build site

on:
  push:
    branches: [master]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: install dependencies
        run: npm install
      
      - name: build site
        run: npm run build
    
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: qwertyyb@foxmail.com
          build_dir: public
          branch: gh-pages
          jekyll: no
          commit_message: "update site"
        
      - name: upload pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: public
