name: transform markdown image urls

on:
  push:
  workflow_dispatch:
    inputs:
      mdfile:
        description: 'markdown file name'
        required: false
  
jobs:
  transform-markdown-image-urls:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: transform images
        uses: qwertyyb/replace-md-images-action@v1.1.0
        with:
          token: ${{ secrets.github_token }}
          bucket: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}
          secretId: ${{ secrets.SECRETID }}
          secretKey: ${{ secrets.SECRETKEY }}
          prefix: '/tmp/md/'
          mdfile: ${{ inputs.mdfile }}
          webhookUrl: ${{ secrets.WEBHOOKURL }}
